#8004表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 8089
spring:
  datasource:
    db1:
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包 com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 111111
    db2:
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包 com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/SCPTPSMS_GUIZ?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 111111
mybatis:
  mapper-locations: classpath:mapper/*.xml