# 微服务的端口号
server:
  port: 8002
# 服务名称
spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 111111


mybatis:
  mapperLocations: classpath:mapper/*.xml     #mapper.xml文件所在位置
  type-aliases-package: springcloud.domain    # 所有Entity别名类所在包

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka #http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#      #此时服务名称  cloud-payment-service 是有两个实例的 cloud-provider-payment8001,cloud-provider-payment8002
      #所以 给具体服务取别名:
#  instance:
#    instance-id: payment8001
#    prefer-ip-address: true       #访问路径可以显示IP地址
#    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
#    lease-expiration-duration-in-seconds: 2
#    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
#    lease-renewal-interval-in-seconds: 2